import type { Contractor } from "@/shared/types";

// Demo data for initial state
export const contractors: Contractor[] = [
    {
        id: '1',
        personalData: {
            firstName: 'Maria',
            lastName: 'González',
            email: 'maria.gonzalez@email.com',
            phone: '+52 555 123 4567',
            country: 'Mexico',
            address: 'Av. Reforma 222, CDMX',
            dateOfBirth: '1990-05-15',
            taxId: 'GOGM900515XXX',
        },
        documents: [
            { id: '1', type: 'id-front', name: 'INE_front.jpg', url: '#', uploadedAt: new Date('2024-01-10'), status: 'approved' },
            { id: '2', type: 'id-back', name: 'INE_back.jpg', url: '#', uploadedAt: new Date('2024-01-10'), status: 'approved' },
            { id: '3', type: 'proof-of-address', name: 'CFE_bill.pdf', url: '#', uploadedAt: new Date('2024-01-10'), status: 'pending' },
        ],
        contractSigned: true,
        contractSignedAt: new Date('2024-01-11'),
        paymentMethod: {
            type: 'bank-transfer',
            bankName: 'BBVA Mexico',
            accountNumber: '****4521',
            currency: 'MXN',
        },
        currentStep: 'verification',
        status: 'pending-verification',
        invitedAt: new Date('2024-01-08'),
        lastUpdatedAt: new Date('2024-01-12'),
        completedSteps: ['personal-data', 'documents', 'contract', 'payment-method'],
    },
    {
        id: '2',
        personalData: {
            firstName: 'James',
            lastName: 'Wilson',
            email: 'james.wilson@email.com',
            phone: '+1 415 555 0123',
            country: 'United States',
            address: '456 Market St, San Francisco, CA',
            dateOfBirth: '1985-08-22',
            taxId: '***-**-4532',
        },
        documents: [
            { id: '4', type: 'id-front', name: 'passport.jpg', url: '#', uploadedAt: new Date('2024-01-12'), status: 'rejected', rejectionReason: 'Image is blurry, please upload a clearer photo' },
        ],
        contractSigned: false,
        currentStep: 'documents',
        status: 'corrections-needed',
        invitedAt: new Date('2024-01-11'),
        lastUpdatedAt: new Date('2024-01-13'),
        completedSteps: ['personal-data'],
    },
    {
        id: '3',
        personalData: {
            firstName: 'Ana',
            lastName: 'Silva',
            email: 'ana.silva@email.com',
            phone: '+55 11 98765 4321',
            country: 'Brazil',
            address: 'Rua Augusta 1200, São Paulo',
            dateOfBirth: '1992-12-03',
            taxId: '123.456.789-00',
        },
        documents: [],
        contractSigned: false,
        currentStep: 'personal-data',
        status: 'in-progress',
        invitedAt: new Date('2024-01-13'),
        lastUpdatedAt: new Date('2024-01-13'),
        completedSteps: [],
    },
    {
        id: '4',
        personalData: {
            firstName: 'Carlos',
            lastName: 'Mendez',
            email: 'carlos.mendez@email.com',
            phone: '+34 612 345 678',
            country: 'Spain',
            address: 'Calle Gran Via 42, Madrid',
            dateOfBirth: '1988-03-17',
            taxId: '12345678Z',
        },
        documents: [
            { id: '5', type: 'id-front', name: 'DNI_front.jpg', url: '#', uploadedAt: new Date('2024-01-09'), status: 'approved' },
            { id: '6', type: 'id-back', name: 'DNI_back.jpg', url: '#', uploadedAt: new Date('2024-01-09'), status: 'approved' },
            { id: '7', type: 'proof-of-address', name: 'utility_bill.pdf', url: '#', uploadedAt: new Date('2024-01-09'), status: 'approved' },
            { id: '8', type: 'tax-document', name: 'tax_cert.pdf', url: '#', uploadedAt: new Date('2024-01-09'), status: 'approved' },
        ],
        contractSigned: true,
        contractSignedAt: new Date('2024-01-10'),
        paymentMethod: {
            type: 'wise',
            email: 'carlos.mendez@email.com',
            currency: 'EUR',
        },
        currentStep: 'verification',
        status: 'approved',
        invitedAt: new Date('2024-01-07'),
        lastUpdatedAt: new Date('2024-01-11'),
        completedSteps: ['personal-data', 'documents', 'contract', 'payment-method', 'verification'],
    },
];